theme: jekyll-theme-chirpy
baseurl: ''
lang: en-UK
timezone: Europe/London
title: "Mairi's Constant"
tagline: Forensics, Linux, Physics and Linguistics
description: >-
  DFIR, Digital Forensics, Security, Hacking, Linux, Physics, Linguistics

url: 'https://tmairi.github.io'
github:
  username: TMairi
twitter:
  username: AstrumMairi

social:
  name: Mairi
  email: false 
  links:
    - https://twitter.com/AstrumMairi     
    - https://github.com/TMairi       
theme_mode: dark
avatar: assets/img/LOGO.png
toc: true
paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# DO NOT change this unless you're a Pro user on Jekyll and Web development,
# Or you think you're smart enough to change other relevant URLs within this template.
#permalink: /posts/:title/
permalink: :year/:month/:title/

collections:
  tabs:
    output: true
    sort_by: order


defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: false
      toc: true
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
